### ISSUE TITLE
ICAPServer.ova Set Guaranteed QoS for rebuild pod - currently over provisioned

### ISSUE THREAD

**Issue by shashanksinha89** [k8-proxy/GW-proxy#239]
Current allocation: 
Limits:
      cpu:     1
      memory:  10000Mi
    Requests:
      cpu:     200m
      memory:  250Mi
QoS Class:       Burstable

**Comment by mahnouman** [comment]
Duplicate of https://github.com/k8-proxy/GW-proxy/issues/222

**Comment by shashanksinha89** [comment]
@mahnouman #222 is reference ticket.  Please don't close this ticket. This issue still needs to be addressed.

@uzfarid fyi

**Comment by shashanksinha89** [comment]
Reference info from pod running on ICAP-03 

```
glasswall@glasswall:~$ kubectl describe pod rebuild-c7b4b3b4-0be6-404f-8125-50bd743f948d -n icap-adaptation
Name:         rebuild-c7b4b3b4-0be6-404f-8125-50bd743f948d
Namespace:    icap-adaptation
Priority:     0
Node:         glasswall/192.168.99.37
Start Time:   Wed, 09 Dec 2020 17:11:31 +0000
Labels:       <none>
Annotations:  cni.projectcalico.org/podIP: 10.42.0.70/32
              cni.projectcalico.org/podIPs: 10.42.0.70/32
Status:       Succeeded
IP:           10.42.0.70
IPs:
  IP:  10.42.0.70
Containers:
  rebuild:
    Container ID:   docker://41d05674d3aad9bae702aad86e7a37058d6539ec0da6dc53f3923069bcc43196
    Image:          glasswallsolutions/icap-request-processing:main-0c9d946
    Image ID:       docker-pullable://glasswallsolutions/icap-request-processing@sha256:b5f0fcfe3907639061c5cbc8b52c2f056348832832627eced5b693249df9f3f1
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 09 Dec 2020 17:11:43 +0000
      Finished:     Wed, 09 Dec 2020 17:11:45 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  10000Mi
    Requests:
      cpu:     200m
      memory:  250Mi
```

**Comment by shashanksinha89** [comment]
Try setting the resources for pod to minimum where pod's performance is not impacted. Reference resource settings that can be tried

```
resources:
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 1000m
      memory: 250Mi

``` 
OR 
```
resources:
    limits:
      cpu: 400m
      memory: 500Mi
    requests:
      cpu: 400m
      memory: 500Mi
```
